import Head from 'next/head'

import Layout from '../components/Layout/Layout'
import Block from '../components/Block/Block'
import Wrap from '../components/Wrap/Wrap'

import Filters from '../components/Filters/Filters'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Block>
          <Wrap>
            <Filters />
          </Wrap>
        </Block>
      </Layout>
    </div>
  )
}
